name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/xaverick/geekclash-backend:${{ github.sha }}

      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ghcr.io/xaverick/geekclash-client:${{ github.sha }}
          build-args: |
            VITE_API_URL=http://api.38.248.14.181.nip.io

      - name: Build and push admin
        uses: docker/build-push-action@v4
        with:
          context: ./admin
          push: true
          tags: ghcr.io/xaverick/geekclash-admin:${{ github.sha }}
          build-args: |
            VITE_API_URL=http://api.38.248.14.181.nip.io

      - name: Update manifests repo
        run: |
          git clone https://x-access-token:${{ secrets.MANIFEST_REPO_TOKEN }}@github.com/Xaverick/quizcraft-manifest-file
          cd quizcraft-manifest-file

          sed -i "s|ghcr.io/xaverick/geekclash-backend:.*|ghcr.io/xaverick/geekclash-backend:${{ github.sha }}|" backend-deployment.yaml
          sed -i "s|ghcr.io/xaverick/geekclash-client:.*|ghcr.io/xaverick/geekclash-client:${{ github.sha }}|" client-deployment.yaml
          sed -i "s|ghcr.io/xaverick/geekclash-admin:.*|ghcr.io/xaverick/geekclash-admin:${{ github.sha }}|" admin-deployment.yaml

          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git diff --quiet || git commit -am "ci: deploy ${{ github.sha }}"
          git push